[versions]
# base
jdk = "25"
minecraft = "26.1.2"
fabric-loader = "0.18.6"
fabric-api = "0.145.4+26.1.2"

# fabric
loom = "1.16-SNAPSHOT"

# mod
sodium = "mc26.1.1-0.8.9-fabric"
lithium = "mc26.1.1-0.23.0-fabric"
iris = "1.10.9+26.1-fabric"
modmenu = "18.0.0-alpha.8"
viafabricplus = "4.5.1"
immediatelyfast = "1.15.1+26.1.1-fabric"
# entityculling = "YSbzFHRt"

# lib
lwjgl = "3.4.1"
smartboot-aio = "1.7.1"
caffeine = "3.1.8"
humbleui-types = "0.2.0"
skija-windows = "0.143.12"
junixsocket = "2.10.1"
java-websocket = "1.6.0"
mp3agic = "0.9.1"
jlayer = "1.0.1"
mp3spi = "1.9.5.4"
jaudiotagger = "2.0.3"
jlayer-google = "1.0.1.4"
mcping = "1.4.2"
reflect = "1.4.0"
jna = "5.12.1"

[libraries]
# Fabric
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# mod
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
lithium = { module = "maven.modrinth:lithium", version.ref = "lithium" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }
viafabricplus = { module = "com.viaversion:viafabricplus", version.ref = "viafabricplus" }
viafabricplus-api = { module = "com.viaversion:viafabricplus-api", version.ref = "viafabricplus" }
immediatelyfast = { module = "maven.modrinth:immediatelyfast", version.ref = "immediatelyfast" }
# entityculling = { module = "maven.modrinth:entityculling", version.ref = "entityculling" }

# lib
smartboot-aio = { module = "io.github.smartboot.socket:aio-core", version.ref = "smartboot-aio" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
humbleui-types = { module = "io.github.humbleui:types", version.ref = "humbleui-types" }
skija-windows = { module = "io.github.humbleui:skija-windows-x64", version.ref = "skija-windows" }
junixsocket-common = { module = "com.kohlschutter.junixsocket:junixsocket-common", version.ref = "junixsocket" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "java-websocket" }
mp3agic = { module = "com.mpatric:mp3agic", version.ref = "mp3agic" }
jlayer = { module = "javazoom:jlayer", version.ref = "jlayer" }
mp3spi = { module = "com.googlecode.soundlibs:mp3spi", version.ref = "mp3spi" }
jaudiotagger = { module = "org:jaudiotagger", version.ref = "jaudiotagger" }
jlayer-google = { module = "com.googlecode.soundlibs:jlayer", version.ref = "jlayer-google" }
mcping = { module = "net.lenni0451:MCPing", version.ref = "mcping" }
reflect = { module = "net.lenni0451:Reflect", version.ref = "reflect" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }

# LWJGL NFD
lwjgl-nfd = { module = "org.lwjgl:lwjgl-nfd", version.ref = "lwjgl" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
